name: Health check

on:
    # FIXME: Please comment this in if you want to use this
    # schedule:
    #     - cron: "*/30 * * * *"
    workflow_dispatch:

jobs:
    health-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: bash run.sh -M actions
              env:
                  DISCORD_WEBHOOK_URI: https://discord.com/api/webhooks/1246640353918845049/KKt_zyY_NfSgWsSjGIFKKnIoGmRDef4uTdnBKsu2zJ-0H21dKBigzYEVwItONiKMsowu
                  HTTP_RESPONSE_CHECK: ${{secrets.HTTP_RESPONSE_CHECK}}
                  TIMEOUT: ${{secrets.TIMEOUT}}
